// Including all the effects you want to use (add in alfabetic order):
#include "effects/colorFill.h"
#include "effects/confetti.h"
#include "effects/debug.h"
#include "effects/glitter.h"
#include "effects/inward.h"
#include "effects/plasma.h"
#include "effects/radar.h"
#include "effects/rider.h"
#include "effects/riderOriginal.h"
#include "effects/sideRain.h"
#include "single.h"
#include "slantBars.h"
#include "threeDee.h"
#include "threeSine.h"
#include "vrain.h"
